// Configuration
export {
  BLUESKY_PROVIDER_ID,
  BLUESKY_DISPLAY_NAME,
  BLUESKY_AUTHORIZATION_ENDPOINT,
  BLUESKY_TOKEN_ENDPOINT,
  BLUESKY_PUSHED_AUTHORIZATION_REQUEST_ENDPOINT,
  BLUESKY_USER_INFO_PATH,
  BLUESKY_HANDLE_RESOLUTION_ENDPOINT,
  BLUESKY_PLC_DIRECTORY_URL,
  BLUESKY_PROTECTED_RESOURCE_METADATA_PATH,
  BLUESKY_AUTHORIZATION_SERVER_METADATA_PATH,
  BLUESKY_CLIENT_METADATA_PATH,
  BLUESKY_JWKS_PATH,
  BLUESKY_CALLBACK_PATH,
  BLUESKY_DEFAULT_SCOPES,
  BLUESKY_CLIENT_NAME,
  BLUESKY_SIGNING_ALGORITHM,
  BLUESKY_CLIENT_ASSERTION_TYPE,
  type BlueskyOAuthConfiguration,
} from './configuration.ts';

// Provider
export {
  blueskySessionResponseSchema,
  parseBlueskySessionResponse,
  blueskyResolveHandleResponseSchema,
  parseBlueskyResolveHandleResponse,
  blueskyDIDDocumentSchema,
  parseBlueskyDIDDocument,
  blueskyProtectedResourceMetadataSchema,
  parseBlueskyProtectedResourceMetadata,
  blueskyAuthorizationServerMetadataSchema,
  parseBlueskyAuthorizationServerMetadata,
  blueskyPushedAuthorizationResponseSchema,
  parseBlueskyPushedAuthorizationResponse,
  blueskyTokenResponseSchema,
  parseBlueskyTokenResponse,
  blueskyScopeIncludesAtproto,
  normalizeBlueskyHandle,
  createBlueskyDIDDocumentURL,
  parseBlueskyServerOrigin,
  findBlueskyPDSURL,
  blueskyDIDDocumentClaimsHandle,
  createBlueskyClientMetadata,
  parseBlueskyCallbackParameters,
  blueskyOAuthProvider,
  createBlueskyAuthorizationURL,
  parseBlueskyUserFromResponse,
  type BlueskySessionResponse,
  type BlueskyResolveHandleResponse,
  type BlueskyDIDDocument,
  type BlueskyProtectedResourceMetadata,
  type BlueskyAuthorizationServerMetadata,
  type BlueskyPushedAuthorizationResponse,
  type BlueskyTokenResponse,
  type BlueskyClientMetadata,
  type BlueskyCallbackParameters,
} from './provider.ts';
