name: "Deactivate: Preview"

# PR이 닫히면 해당 preview 배포를 비활성화한다.

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  deactivate:
    runs-on: ubuntu-latest
    name: Deactivate preview deployment
    permissions:
      deployments: write
    steps:
      - name: Deactivate preview environment
        uses: strumwolf/delete-deployment-environment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: preview
          onlyDeactivateDeployments: true
